on:
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/pikachu.pem
          chmod 600 ~/.ssh/pikachu.pem
          ssh-keyscan -H ${{ secrets.SSH_HOST}} >> ~/.ssh/known_hosts
      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/pikachu.pem -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            cd ~/Desktop/Services/Karaoke_with_discord || exit 1 

            echo "Pulling latest code..."
            git pull origin main
            cd backend || exit 1

            echo "Installing latest requirement"
            pip install -r requirement.txt

            echo "Stopping existing backend"
            if tmux has-session -t karaoke_backend 2>/dev/null; then
              tmux kill-session -t karaoke_backend
            fi

            echo "Starting new backend"
            tmux new-session -d -s karaoke_backend '
              python3.8 backend.py
            '
            echo "Deployment Completed"
          EOF
            
